# ndfc_network_replaced_all/tasks/main.yml
---
- name: main replaced Network FABRIC {{ fabric_name }}
  include_tasks: worker.yml
  loop: "{{ lookup('ansible.builtin.dict', networks) }}"
  when: "fabric_name in network.value.fabric"
  loop_control:
    loop_var: network
