ansible_connection: ansible.netcommon.httpapi
ansible_network_os: cisco.dcnm.dcnm
ansible_httpapi_validate_certs: no
ansible_httpapi_use_ssl: yes
ansible_user: admin
device_username: admin
device_password: mypassword
ansible_password: mypassword
