vrfs:
  fabric_1_vrf_1:
    name: fabric_1_vrf_1
    fabric: "{{ vxlan_fabric.f1.FABRIC_NAME }}"
    vrf_name: v1
    vrf_id: 63031
    vlan_id: 3031
    import_vpn_rt: "{{ vxlan_fabric.f1.BGP_AS }}:63032"
    import_evpn_rt: "{{ vxlan_fabric.f1.BGP_AS }}:63032"
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"

  fabric_1_vrf_2:
    name: fabric_1_vrf_2
    fabric: "{{ vxlan_fabric.f1.FABRIC_NAME }}"
    vrf_name: v2
    vrf_id: 63032
    vlan_id: 3032
    import_vpn_rt: "{{ vxlan_fabric.f1.BGP_AS }}:63031"
    import_evpn_rt: "{{ vxlan_fabric.f1.BGP_AS }}:63031"
    vrf_template: Default_VRF_Universal
    vrf_extension_template: Default_VRF_Extension_Universal
    service_vrf_template: null
    attach:
    - ip_address: "{{ devices.leaf_1.ip }}"
    - ip_address: "{{ devices.leaf_2.ip }}"
    - ip_address: "{{ devices.leaf_3.ip }}"
