# ndfc_rest_config_deploy_all/tasks/main.yml
---
- name: main REST POST config-save FABRIC {{ fabric_name }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-save"
    json_data: "{{ vars_dict | to_json }}"
  vars:
    ansible_connection: httpapi
    vars_dict:

- name: main REST POST config-deploy FABRIC {{ fabric_name }}
  cisco.dcnm.dcnm_rest:
    method: POST
    path: "/appcenter/cisco/ndfc/api/v1/lan-fabric/rest/control/fabrics/{{ fabric_name }}/config-deploy"
    json_data: "{{ vars_dict | to_json }}"
  vars:
    ansible_connection: httpapi
    vars_dict:
      forceShowRun: "{{ forceShowRun }}"
      inclAllMSDSwitches: "{{ inclAllMSDSwitches }}"